name = "sma-data-pwa"
type = "service"
main = "src/index.ts"

compatibility_date = "2025-01-09"

# Static Assets
[assets]
directory = "public"

[env.production]
vars = { ENVIRONMENT = "production" }
secrets = ["SMA_READER_ACCESS"]
