name = "sma-data-pwa"
# Point to the PWA worker that serves auth.html and proxies API
main = "pwa/src/index.ts"

# Align with latest deploy date
compatibility_date = "2025-12-27"

# Static Assets
[assets]
directory = "./public"

[env.production]
vars = { ENVIRONMENT = "production" }
